name: Fetch RSS Feed

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write  # 👈 dit geeft schrijfpermissie aan de actie

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch RSS feed
        run: |
          mkdir -p RSS/data
          curl -s "https://alarmeringen.nl/feeds/region/midden-en-west-brabant.rss" > RSS/feed.xml

      - name: Parse RSS to JSON
        run: python3 RSS/fetch_and_parse.py

      - name: Commit and push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add RSS/data/feed.json
          git commit -m "⏱️ Auto-update feed" || echo "No changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
