name: Update Skinport Prices

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:      # Allows manual triggering

jobs:
  update-prices:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Create data directory
        run: mkdir -p data

      - name: Run price update script
        run: node scripts/update-prices.js

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data/skinport-prices.json
          git diff --staged --quiet || (git commit -m "Update Skinport prices" && git push)
